### ISSUE TITLE
Transfer repository to organisation account

### ISSUE THREAD

**Issue by sabianroberts** [phoenixprojectsoftware/zamnhl-sdk#3]
I made the @thephoenixprojectsoftware account unaware of GitHub teams. When I found out about it, I created the @phoenixprojectsoftware account. Now that private repositories with unlimited collaborators are free for teams, we should transfer this repository (and the rest) to @phoenixprojectsoftware.

**Comment by thephoenixprojectsoftware** [comment]
Done!
