### ISSUE TITLE
Consider switching to Half-Life ADM

### ISSUE THREAD

**Issue by sabianroberts** [phoenixprojectsoftware/zamnhl-sdk#5]
Half-Life ADM just seems much better and more complete than Grey Source. Sure, we'll have to make more modifications to it, but at the end of the day I think it'll be worth it.

**Comment by reductor** [comment]
Why BASS and not one of the many other libraries such as OpenAL?

**Comment by sabianroberts** [comment]
You could do OpenAL if you want to, I wasn't thinking of the other libraries... I'll update the issue

**Comment by sabianroberts** [comment]
Welp. It's official! We're moving to ADM.

**Comment by sabianroberts** [comment]
so yeah we are moving back
