### ISSUE TITLE
Version info doesn't print properly at commit d90b717

### ISSUE THREAD

**Issue by sabianroberts** [phoenixprojectsoftware/zamnhl-sdk#6]
d90b717640ebecce1c7686e7a10941250ff6248a

# What it's supposed to print
**'Half-Life: Zombies Ate My Neighbours' is running Grey Source 2020 Proprietary [build 2005-Z] built on (DATE)**

**Type of build: Proprietary**

**Grey Source 2020 Proprietary by The Phoenix Project**

**The game SDK can be found at https://github.com/phoenixprojectsoftware/zamnhl-sdk**

**The engine SDK can be found at https://github.com/phoenixprojectsoftware/greysource**

# What it prints instead

```
'Half-Life: Zombies Ate My Neighbours' is running 
 Type of build: 
 
 The game SDK can be found at 
 The engine SDK can be found at 
```

**Comment by barney-heatwave** [comment]
b33caaf8d1f36c44c5e7314897298568190992b2
